## To test an Analyzer of Responder with docker: 
#
# Copy this file in the folder of an analyzer or a responder and name it Dockerfile
## edit it and Change variables
#
# - {workername} by the folder name of the analyzer or responder
# - {command} by the value of the `command` in a JSON file
# 
# Save and run: 
#
# docker build -t cortexneurons/{flavor_name}:devel  with {flavor_name} the name of the analyzer of responder in the JSON file
#
# 



FROM python:3-alpine
# Specific alpine setup to support libmagic
# RUN apk add --no-cache file-dev && rm -rf /var/cache/apk/*
WORKDIR /worker
COPY requirements.txt {worker_name}/
RUN test ! -e {worker_name}/requirements.txt || pip install --no-cache-dir -r {worker_name}/requirements.txt
COPY . {worker_name}/
ENTRYPOINT ["python", "{command}"]
