FROM python:3-alpine

LABEL author="CERT-BDF" \
      license="AGPL-V3" \
      source="https://github.com/TheHive-Project/Cortex-Analyzers" \
      title="DNSDB" \
      url="https://github.com/TheHive-Project/Cortex-Analyzers" \
      vendor="TheHive" \
      version="2.0.0"

WORKDIR /worker

COPY . DNSDB
RUN pip install --no-cache-dir -r DNSDB/requirements.txt

ENTRYPOINT DNSDB/dnsdb.py